version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "sh /app/web.entrypoint.sh"
    env_file:
      - ../.env
    volumes:
      - ../src/:/app/src/
    depends_on:
    - mongodb
    - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge